function b_cons = bfunc(T,Fmax,thmax)
%BFUNC
%    B_CONS = BFUNC(T,FMAX,THMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    26-Apr-2023 13:46:16

b_cons = [Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;thmax;thmax];
