function b_cons = bfunc(T,Fmax,thmax,dphimax)
%BFUNC
%    B_CONS = BFUNC(T,FMAX,THMAX,DPHIMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Apr-2023 00:09:48

b_cons = [Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;thmax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax;dphimax];
